package com.myata_bot.core.botapi;

public enum BotState {
    //ADMIN,
    MAIN_ADMIN,
    ASK_ADMIN_NAME,
    ASK_ADMIN_TO_DO,
    COLLECT_ADMIN_TO_DO,
    COLLECT_ADMIN_NAME,
    ASK_ADMIN_CONFIRM_RESERVATION,
    COLLECT_ADMIN_CONFIRM_RESERVATION,
    COLLECT_ADMIN_DELETE_RESERVATION,
    COLLECT_ADMIN_ARRIVED_RESERVATION,
    //USER
    FILLING_PROFILE,
    FILLING_RESERVATION,
    ASK_NAME,
    COLLECT_DATE_ASK_TIME,
    COLLECT_TIME_ASK_AMOUNT_OF_PEOPLE,
    COLLECT_AMOUNT_OF_PEOPLE_ASK_PHONE_NUMBER,
    COLLECT_COMMENT_AND_COMPLETE,
    COLLECT_PHONE_NUMBER_ASK_COMMENT,
    MAIN,
    ASK_TO_DO_FROM_UNKNOWN,
    ASK_TO_DO,
    COLLECT_TO_DO
}
